config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  resources :places do
     resources :posts, except: [:index]
     resources :invites, except: [:index]
     post '/leave' => 'places#leave', as: :leave
   end

   resources :invites, only: [:index]

   scope '/invite', :controller => :invites do
    post :accept_invite
    post :decline_invite
  end

   resources :posts, only: [] do
     resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
      resources :users, :only => [:show]

  get 'about' => 'welcome#about'

  root 'welcome#index'

  authenticate :user, lambda { |u| u.is_admin? } do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :user_group
  belongs_to :sender, :class_name => 'User'
  belongs_to :recipient, :class_name => 'User'

  before_create :generate_token

  def generate_token
     self.token = Digest::SHA1.hexdigest([self.place_id, Time.now, rand].join)
  end

  before_save :check_user_existence

   def check_user_existence
      recipient = User.find_by_email(email)
     if recipient
        self.recipient_id = recipient.id
     end
   end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

  before_action :require_sign_in

  def index
    @invites = Invite.where("email=?", current_user.email)
  end

  def new
    @place = Place.find(params[:place_id])
    @user_group = UserGroup.where(place_id: [@place.id])
    @invite = Invite.new
  end



  def create
    @place = Place.find(params[:place_id])
    @invite = Invite.new(invite_params)
    # emails = params[:invite_emails].split(', ')
    # emails.each do |email|
      @invite.sender_id = current_user.id
      @user_group = UserGroup.where(place_id: [@place.id])
      @invite.place_id = @place.id

      if @invite.save

        #if the user already exists
        if @invite.recipient != nil

            #check if the user is already apart of the UserGroup
            if @user_group = UserGroup.where('place_id=? AND user_id=?',@place.id, current_user.id) != nil
              flash[:warning] = "#{@invite.recipient.name} is already in this group."
              redirect_to @place

            else

             #send a notification email
             InviteMailer.existing_user_invite(@invite,@place).deliver


             flash[:notice] = "Invitation was sent!."
             redirect_to @place
           end
          #user does not exist
          else
             InviteMailer.new_user_invite(@invite,@place, new_user_registration_path(:invite_token => @invite.token)).deliver
             flash[:notice] = "Invitation was sent!."
             redirect_to @place
        end
      #did not save
      else
        flash[:alert] = "Invitation was not sent. Please check your email and try again."
        redirect_to new_invite_path
      end

  end

  def accept_invite
    @invite = Invite.find(params[:id])
    @place = Place.find(@invite.place_id)

    @invite.accepted = true

    #Add the user to the user group
    current_user.places << @place

    if @invite.save
       flash[:notice] = "#{@place.name} invite was accepted."
       redirect_to @place
    else
      flash.now[:alert] = "Error saving. Please try again."
      redirect_to invites_path
    end
  end

  def decline_invite
    @invite = Invite.find(params[:id])
    @place = Place.find(@invite.place_id)

    @invite.accepted = false
    if @invite.save
       flash[:notice] = "#{@place.name} invite was declined."
       redirect_to invites_path
    else
      flash.now[:alert] = "Error saving. Please try again."
      redirect_to invites_path
    end
  end


  private

  def invite_params
    params.require(:invite).permit(:email)
  end

end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/index.html.erb
<h1>Invites</h1>


  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Group</th>
        <th>Contribution</th>
        <th>Invited By</th>
        <th>Sent</th>
        <th>Status</th>
      </tr>
    </thead>
      <tbody>
        <% @invites.each_with_index do |invite, index| %>
        <tr>
          <td><%=Place.find(invite.place_id).name%></td>
          <td>$20</td>
          <td><%=User.find(invite.sender_id).name%></td>
          <td><%=time_ago_in_words(invite.created_at.to_time)%> ago</td>
          <%if invite.accepted == nil%>
            <td>
              <%=link_to 'Accept'.html_safe, accept_invite_path(:id=>invite.id), :method => 'post', :remote => true, :class => "btn btn-success btn-sm", :disable_with => ''%>
              <%=link_to 'Decline'.html_safe, decline_invite_path(:id=>invite.id), :method => 'post', :remote => true, :class => "btn btn-default btn-sm", :invite_id => invite.id, :status => false, :disable_with => ''%>
            </td>
          <%else%>
            <%if invite.accepted%>
              <td>Accepted</td>
            <%else%>
              <td>Declined</td>
            <%end%>
          <%end%>
        </tr>
          <% end %>
      </tbody>

    </table>

  </div>

app/views/invites/new.html.erb
<%= form_for [@place, @invite] do |f| %>
    <%= f.hidden_field :place_id, :value => @invite.place_id %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.submit 'Send' %>
<% end %>