config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  resources :places do
     resources :posts, except: [:index]
     resources :invites, except: [:index]
     post '/leave' => 'places#leave', as: :leave
   end

   resources :invites, only: [:index]

   scope '/invite', :controller => :invites do
    post :accept_invite
    post :decline_invite
  end

   resources :posts, only: [] do
     resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
      resources :users, :only => [:show]

  get 'about' => 'welcome#about'

  root 'welcome#index'

  authenticate :user, lambda { |u| u.is_admin? } do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments, dependent: :destroy
  belongs_to :place
  belongs_to :user
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  after_create :create_favorite
  after_create :create_vote

  default_scope { order('rank DESC') }


  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :link, length: { minimum: 10 }, presence: true
  validates_format_of :link, :with => /\/\/(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=|embed\/)?([a-z0-9_\-]+)/i , :on => :create
  validates :place, presence: true
  validates :user, presence: true

  def up_votes
     votes.where(value: 1).count
   end

   def down_votes
     votes.where(value: -1).count
   end

   def points
     votes.sum(:value)
   end

   def update_rank
     age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
     new_rank = points + age_in_days
     update_attribute(:rank, new_rank)
   end


   private

   def create_favorite
     Favorite.create(post: self, user: self.user)
     FavoriteMailer.new_post(self).deliver_now
   end

   def create_vote
     user.votes.create(value: 1, post: self)
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  helper_method :get_link_info
  helper_method :strip_link_id

  before_action :require_sign_in, except: :show

  def show
    @post = Post.find(params[:id])
    @member_count = UserGroup.where(:place_id [params[:place_id]]).size
  end

  def new
    @place = Place.find(params[:place_id])
    @post = Post.new
  end

  def create

     @place = Place.find(params[:place_id])
     @post = @place.posts.build(post_params)
     @post.user = current_user


     if @post.save
       flash[:notice] = "Post was saved."
       redirect_to [@place, @post]
     else
       flash.now[:alert] = "There was an error saving the post. Please try again."
       render :new
     end
   end

   def destroy
     @post = Post.find(params[:id])

     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
       redirect_to @post.place
     else
       flash.now[:alert] = "There was an error deleting the post."
       render :show
     end
   end


   def edit
      @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
      @post.assign_attributes(post_params)


      if @post.save
        flash[:notice] = "Post was updated."
        redirect_to [@post.place, @post]
      else
        flash.now[:alert] = "There was an error saving the post. Please try again."
        render :edit
      end
    end

  def get_link_info(link)
    link_obj = LinkThumbnailer.generate(link)
    return link_obj
  end

  def strip_link_id(link)
    link.reverse!
    if link.include? '='
      codeArray = link.split('=',2)
    else
      codeArray = link.split('/',2)
    end
    code = codeArray[0]
    code.reverse!
    return code
  end



    private

    def post_params
      params.require(:post).permit(:title, :link, :body)
    end

end

app/helpers/posts_helper.rb
module PostsHelper

  def user_is_authorized_for_post?(post)
      current_user && (current_user == post.user || current_user.is_admin?)
   end

end

app/views/posts/_form.html.erb
<%= form_for [place, post] do |f| %>
  <% if post.errors.any? %>
      <div class="alert alert-danger">
        <h4><%= pluralize(post.errors.count, "error") %>.</h4>
        <ul>
          <% post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <%end%>
  <%= form_group_tag(post.errors[:image]) do %>
    <%= f.label :image %>
    <%= f.text_field :image, class: 'form-control', placeholder: "Enter link to your cover photo" %>
  <%end%>
  <%= form_group_tag(post.errors[:link]) do %>
    <%= f.label :link %>
    <%= f.text_field :link, class: 'form-control', placeholder: "Enter link to your proposal" %>
  <%end%>
  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post description" %>
  <%end%>
  <%= form_group_tag(post.errors[:expense]) do %>
    <%= f.label :expense %>
    <%= f.number_field :expense, class: 'form-control', placeholder: "Enter total expense" %>
  <%end%>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
    <%= render partial: 'votes/voter', locals: { post: post } %>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to post.title, place_post_path(post.place, post) %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
      <%= post.comments.count %> Comments
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

 <div class="row">
   <div class="col-md-4">
     <!-- <p>Guidelines for posts</p>
     <ul>
       <li>Capitalize your Title.</li>
       <li>Youtube URL must be original URL link or Sharable link ("Start at" is not supported).</li>
     </ul> -->
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { place: @post.place, post: @post } %>
   </div>
 </div>

app/views/posts/new.html.erb
<h1>New Post</h1>

 <div class="row">
   <div class="col-md-4">
     <!-- <p>Guidelines for posts</p>
     <ul>
       <li>Capitalize your Title.</li>
       <li>Youtube URL must be original URL link or Sharable link ("Start at" is not supported).</li>
     </ul> -->
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { place: @place, post: @post } %>
   </div>
 </div>

app/views/posts/show.html.erb
<div class="media">
  <div style='float:top'>
    <div><%= image_tag( @post.image, width: '75%') %></div>
  </div>
  <div style="float:left; margin-top: 20px;">
   <%= render partial: 'votes/voter', locals: { post: @post } %>
  </div>
   <h1>
     <%= @post.title %> <br>
     <small>
       submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
     </small>
   </h1>
 </div>
<div class="row">
  <div class="col-md-8">
    <h3><%=number_to_currency(@post.expense/100)%></h3>
    <small><%=number_to_currency(@post.expense/100/@member_count)%> per person</small>
    <p><%= @post.body %></p>
    <% if current_user %>
     <%= render partial: 'favorites/favorite', locals: { post: @post } %>
    <% end %>
    <div>
      <h3>Comments</h3>
      <% if @post.comments.count == 0%>
        <small>There are currently no comments for this post. 😕</small>
      <%else%>
        <%= render @post.comments %>
      <%end%>
    </div>
    <% if current_user %>
       <%= render 'comments/form', comment: Comment.new, post: @post %>
     <% end %>
     <div class="col-md-4">
     <h3>
       <%= pluralize(@post.points, 'point') %>
       <div>
         <small>
           <%= pluralize(@post.up_votes, 'up vote') %>,
           <%= pluralize(@post.down_votes, 'down vote') %>
         </small>
       </div>
     </h3>
   </div>
  </div>
<div class="col-md-4">
  <%if user_is_authorized_for_post?(@post)%>
      <%= link_to "Edit", edit_place_post_path(@post.place, @post), class: 'btn btn-primary' %>
      <%= link_to "Delete Post", [@post.place, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
  <%end%>
  </div>
</div>

<!-- <script>

  $(document).ready(function(){

    //Check if the current URL contains '#'
    if(document.URL.indexOf("#")==-1)
    {
    // Set the URL to whatever it was plus "#".
    url = document.URL+"#";
    location = "#";

    //Reload the page
    location.reload(true);

    }
    });

</script> -->