config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  resources :places do
     resources :posts, except: [:index]
     resources :invites, except: [:index]
     post '/leave' => 'places#leave', as: :leave
   end

   resources :invites, only: [:index]

   scope '/invite', :controller => :invites do
    post :accept_invite
    post :decline_invite
  end

   resources :posts, only: [] do
     resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
      resources :users, :only => [:show]

  get 'about' => 'welcome#about'

  root 'welcome#index'

  authenticate :user, lambda { |u| u.is_admin? } do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :users
  has_many :user_groups
  has_many :users, through: :user_groups
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController


  before_action :require_sign_in


  def index
    @my_places = current_user.places
  end

  def show
    @place = Place.find(params[:id])
    @member_count = UserGroup.where(:place_id [params[:id]]).size
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    current_user.places << @place

     if @place.save
       redirect_to @place, notice: "Place was saved successfully."
     else
       flash.now[:alert] = "Error creating place. Please try again."
       render :new
     end
   end

   def edit
     @place = Place.find(params[:id])
   end

   def update
     @place = Place.find(params[:id])

     @place.assign_attributes(place_params)

     if @place.save
        flash[:notice] = "Place was updated."
       redirect_to @place
     else
       flash.now[:alert] = "Error saving place. Please try again."
       render :edit
     end
   end

   def leave
    @place = Place.find(params[:place_id])

    @user_group = UserGroup.where('place_id=? AND user_id=?',@place.id, current_user.id)


    if @user_group.destroy_all
     flash[:notice] = "You have left the group: \"#{@place.name}\"."
     redirect_to places_path
   else
     flash.now[:alert] = "There was an error leaving the group: \"#{@place.name}\"."
     render :show
   end
   end

   def destroy
     @place = Place.find(params[:id])

     if @place.destroy
       flash[:notice] = "\"#{@place.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the place."
       render :show
     end
   end

   private

   def place_params
     params.require(:place).permit(:name, :link, :description)
   end

end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/edit.html.erb
<h1>Edit Group</h1>

 <div class="row">
   <div class="col-md-4">
     <!-- <p>Guidelines for places:</p>
     <ul>
       <li>Never insult goats.</li>
       <li>Smile when you type.</li>
     </ul> -->
   </div>
   <div class="col-md-8">
     <%= form_for @place do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter place name" %>
       </div>
       <div class="form-group">
         <%= f.label :link %>
         <%= f.text_field :link, class: 'form-control', placeholder: "Enter place image URL" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">
         <%= f.label :contribution %>
         <%= f.number_field :contribution, class: 'form-control', placeholder: "Enter monthly contribution" %>
       </div>
       <%= f.submit "Save", class: 'btn btn-primary' %>
     <% end %>




   </div>
 </div>

app/views/places/index.html.erb
<h1>My Groups</h1>

 <div class="row">
   <div class="col-md-8">
     <% @my_places.each do |topic| %>
       <div class="media">
         <%= link_to image_tag(topic.link, width: '75%'),topic %>
         <div class="media-body">
           <br>

           <h4 class="media-heading">
             <%= link_to topic.name, topic %>
           </h4>
           <small>
             <%= topic.description %>
           </small>
         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">
     <br>

     <%if current_user%>
        <%= link_to "New Group", new_place_path, class: 'btn btn-primary' %>
     <%end%>

     <br>
     <br>

   </div>
 </div>

app/views/places/new.html.erb
<h1>New Group</h1>

 <div class="row">
   <div class="col-md-4">
     <!-- <p>Guidelines for Groups:</p>
     <ul>
       <li>Make sure it is an accessable location.</li>
       <li>Never insult goats.</li>
       <li>Smile when you type.</li>
     </ul> -->
   </div>
   <div class="col-md-8">
     <%= form_for @place do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter group name" %>
       </div>
       <div class="form-group">
         <%= f.label :link %>
         <%= f.text_field :link, class: 'form-control', placeholder: "Enter group image URL" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter group description" %>
       </div>
       <div class="form-group">
         <%= f.label :contribution %>
         <%= f.number_field :contribution, class: 'form-control', placeholder: "Enter monthly contribution" %>
       </div>
       <%= f.submit "Save", class: 'btn btn-primary' %>
     <% end %>
   </div>
 </div>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>
<%= image_tag( @place.link, width: '75%') %>
<h3>Funds: <%=number_to_currency(@place.total_funds/100)%></h3>
<small>Monthly Contribution: <%=number_to_currency(@place.contribution/100)%></small>

<p class="lead"><%= @place.description %></p>

<%if current_user%>
  <%= link_to "Edit Group", edit_place_path, class: 'btn btn-primary' %>

  <%if current_user.is_admin?%>
    <%= link_to "Delete Group", @place, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this place?' } %>
  <%end%>
<%end%>


<div style='float:top'>
  <h3 style="color:grey">Top rated ideas for <%=@place.name%>.👇</h3>
 <div id="ytplayer"></div>
</div>

<div class="row">
  <div class="col-md-8">
    <div>
      <h3>👍Vote👎 Below or <%= link_to "Add a Post!", new_place_post_path(@place), class: 'btn btn-primary' %></h3>
    </div>
    <% @place.posts.each do |post| %>
      <div class="media">
        <div style='float:top'>
          <%= link_to image_tag(post.image, width: '45%'),place_post_path(@place, post) %>
         </div>
        <%= render partial: 'votes/voter', locals: { post: post } %>
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to post.title, place_post_path(@place, post) %>
          </h4>
          <small>
            submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
             <%= pluralize(post.comments.count, 'Comment') %>
           </small>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <div class="col-md-4">
    <%= link_to "Add Member", new_place_invite_path(@place), class: 'btn btn-primary' %>
  </div>
  <div class="col-md-4">
    <%=link_to 'Leave Group'.html_safe, place_leave_path(@place), :method => 'post', :remote => true, :class => "btn btn-default btn-sm", data: { confirm: 'Are you sure you want to leave this group? You will need to receive a new invite to re-join.' }, :disable_with => '' %>
  </div>

  <br>
  <br>
  <br>
</div>

<script>

 // $(document).ready(function(){
 //
 //   //Check if the current URL contains '#'
 //   if(document.URL.indexOf("#")==-1)
 //   {
 //   // Set the URL to whatever it was plus "#".
 //   url = document.URL+"#";
 //   location = "#";
 //
 //   //Reload the page
 //   location.reload(true);
 //
 //   }
 //   });
</script>