config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  resources :places do
     resources :posts, except: [:index]
     resources :invites, except: [:index]
     post '/leave' => 'places#leave', as: :leave
   end

   resources :invites, only: [:index]

   scope '/invite', :controller => :invites do
    post :accept_invite
    post :decline_invite
  end

   resources :posts, only: [] do
     resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
      resources :users, :only => [:show]

  get 'about' => 'welcome#about'

  root 'welcome#index'

  authenticate :user, lambda { |u| u.is_admin? } do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

   validates :body, length: { minimum: 5 }, presence: true
   validates :user, presence: true

   after_create :send_favorite_emails

   private

   def send_favorite_emails
     post.favorites.each do |favorite|
       FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
     end
   end
   
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :user_group
  belongs_to :sender, :class_name => 'User'
  belongs_to :recipient, :class_name => 'User'

  before_create :generate_token

  def generate_token
     self.token = Digest::SHA1.hexdigest([self.place_id, Time.now, rand].join)
  end

  before_save :check_user_existence

   def check_user_existence
      recipient = User.find_by_email(email)
     if recipient
        self.recipient_id = recipient.id
     end
   end

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :users
  has_many :user_groups
  has_many :users, through: :user_groups
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments, dependent: :destroy
  belongs_to :place
  belongs_to :user
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  after_create :create_favorite
  after_create :create_vote

  default_scope { order('rank DESC') }


  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :link, length: { minimum: 10 }, presence: true
  validates_format_of :link, :with => /\/\/(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=|embed\/)?([a-z0-9_\-]+)/i , :on => :create
  validates :place, presence: true
  validates :user, presence: true

  def up_votes
     votes.where(value: 1).count
   end

   def down_votes
     votes.where(value: -1).count
   end

   def points
     votes.sum(:value)
   end

   def update_rank
     age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
     new_rank = points + age_in_days
     update_attribute(:rank, new_rank)
   end


   private

   def create_favorite
     Favorite.create(post: self, user: self.user)
     FavoriteMailer.new_post(self).deliver_now
   end

   def create_vote
     user.votes.create(value: 1, post: self)
   end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_groups
  has_many :places, through: :user_groups
  has_many :invitations, :class_name => "Invite", :foreign_key => 'recipient_id'
  has_many :sent_invites, :class_name => "Invite", :foreign_key => 'sender_id'


  validates :name, presence: true

  def is_admin?
    self.email && ENV['ADMIN_EMAILS'].to_s.include?(self.email)
  end

  def favorite_for(post)
     favorites.where(post_id: post.id).first
   end

   def avatar_url(size)
     gravatar_id = Digest::MD5::hexdigest(self.email).downcase
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
   end

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  has_many :invites
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

end

private

   def update_post
     post.update_rank
   end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  helper_method :get_link_info
  helper_method :strip_link_id

  before_action :require_sign_in, except: :show

  def show
    @post = Post.find(params[:id])
    @member_count = UserGroup.where(:place_id [params[:place_id]]).size
  end

  def new
    @place = Place.find(params[:place_id])
    @post = Post.new
  end

  def create

     @place = Place.find(params[:place_id])
     @post = @place.posts.build(post_params)
     @post.user = current_user


     if @post.save
       flash[:notice] = "Post was saved."
       redirect_to [@place, @post]
     else
       flash.now[:alert] = "There was an error saving the post. Please try again."
       render :new
     end
   end

   def destroy
     @post = Post.find(params[:id])

     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
       redirect_to @post.place
     else
       flash.now[:alert] = "There was an error deleting the post."
       render :show
     end
   end


   def edit
      @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
      @post.assign_attributes(post_params)


      if @post.save
        flash[:notice] = "Post was updated."
        redirect_to [@post.place, @post]
      else
        flash.now[:alert] = "There was an error saving the post. Please try again."
        render :edit
      end
    end

  def get_link_info(link)
    link_obj = LinkThumbnailer.generate(link)
    return link_obj
  end

  def strip_link_id(link)
    link.reverse!
    if link.include? '='
      codeArray = link.split('=',2)
    else
      codeArray = link.split('/',2)
    end
    code = codeArray[0]
    code.reverse!
    return code
  end



    private

    def post_params
      params.require(:post).permit(:title, :link, :body)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :require_sign_in

  def up_vote
       update_vote(1)
       redirect_to :back
  end

  def down_vote
     update_vote(-1)
     redirect_to :back
  end

  def neutral_vote
     update_vote(0)
  end

   private
   def update_vote(new_value)
     @post = Post.find(params[:post_id])
     @vote = @post.votes.where(user_id: current_user.id).first

     if @vote
       @vote.update_attribute(:value, new_value)
     else
       @vote = current_user.votes.create(value: new_value, post: @post)
     end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_group_tag(errors, &block)
     css_class = 'form-group'
     css_class << ' has-error' if errors.any?
     content_tag :div, capture(&block), class: css_class
   end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
      current_user && (current_user == comment.user || current_user.is_admin?)
   end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def user_is_authorized_for_post?(post)
      current_user && (current_user == post.user || current_user.is_admin?)
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoCoin</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'https://cdn.shopify.com/s/files/1/1061/1924/products/Airplane_Emoji_large.png?v=1458744089' %>
    <%= stylesheet_link_tag    'nav', media: 'all' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">CoCoin</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Groups", places_path %> <span class="sr-only">(current)</span></li>
            <li><%= link_to "Invites", invites_path %> <span class="sr-only">(current)</span></li>
            <li><%= link_to "About", about_path %></li>

          </ul>
          <!-- <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search for Group">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form> -->
          <ul class="nav navbar-nav navbar-right" style="margin:2vw; font-size: 16px;">
            <li>
                <div >
                <%if user_signed_in?%>
                  <%if current_user.is_admin? %>
                  <%=  link_to 'Admin', admin_dashboard_path %>
                  <%end%>
                <%= link_to user_path(current_user) do %>
                  <%= image_tag current_user.avatar_url(48), class: 'gravatar', style: 'width:24px;'%>
                  <%= current_user.name%>
                <%end%>
                   | <%= link_to "Sign Out", destroy_user_session_path, :method => 'delete' %>
                <%else%>
                  <%= link_to "Sign In", new_user_session_path %>
                  or
                  <%= link_to "Sign Up", new_user_registration_path %>
                <%end%>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>


      <!-- <ul class="topnav" id="myTopnav" style="color:#717171">
        <li class="pull-left" style="color:#717171" ><%= link_to "Wherenext.TV", root_path %></li>
        <li><%= link_to "", root_path %></li>
        <li><%= link_to "Places", places_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li class="pull-right" style="margin-top:-10px;">
          <div >
            <%if user_signed_in?%>
              <%if current_user.is_admin? %>
              <%=  link_to 'Admin', admin_dashboard_path %>
              <%end%>
            <%= link_to user_path(current_user) do %>
              <%= image_tag current_user.avatar_url(48), class: 'gravatar' %>
              <%= current_user.name%>
            <%end%>
               | <%= link_to "Sign Out", destroy_user_session_path, :method => 'delete' %>
            <%else%>
              <%= link_to "Sign In", new_user_session_path %>
              or
              <%= link_to "Sign Up", new_user_registration_path %>
            <%end%>
          </div>
        </li>
        <li class="icon">
          <a href="javascript:void(0);" onclick="myFunction()">&#9776;</a>
        </li>
      </ul> -->

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
      <% elsif flash[:warning] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:warning] %>
        </div>
      <% end %>

    <div class="container">
      <%= yield %>
    </div>

    <script>
      function myFunction() {
      var x = document.getElementById("myTopnav");
      if (x.className === "topnav") {
          x.className += " responsive";
      } else {
          x.className = "topnav";
      }
  }
    </script>

  </body>
  </html>